name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Configurer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generer le wrapper Gradle
        run: gradle wrapper --gradle-version 8.7

      - name: Rendre gradlew executable
        run: chmod +x ./gradlew

      - name: Compiler APK Debug
        run: ./gradlew assembleDebug --stacktrace

      - name: Publier APK (Release)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: "Build #${{ github.run_number }}"
          files: app/build/outputs/apk/debug/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
